name: dispatch

on: workflow_dispatch

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - run: |
          git config user.name "alessa"
          git config user.email "alessa@silenthillmuseum.org"
          git commit --allow-empty -m "update progress"
          git push
